version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "dao;y"

    reviewers:
      - "damger9"

    assignees:
      - "damger92"
    labels:
      - "npm dependencies"
    commit-message: 
      prefix: "npm"
